const PDFDocument = require('pdfkit');

class PDFService {
    generatePlagiarismReport(data, userInfo = {}) {
        return new Promise((resolve, reject) => {
            try {
                const doc = new PDFDocument({
                    size: 'A4',
                    margin: 50,
                    info: {
                        Title: 'Plagiarism Check Report',
                        Author: 'Plagiarism Checker Pro',
                        Subject: 'Plagiarism Analysis Report',
                        Keywords: 'plagiarism, report, analysis',
                        Creator: 'Plagiarism Checker Pro v1.0',
                        CreationDate: new Date()
                    }
                });

                const chunks = [];
                doc.on('data', chunk => chunks.push(chunk));
                doc.on('end', () => resolve(Buffer.concat(chunks)));
                doc.on('error', reject);

                // Add header
                this.addHeader(doc, userInfo);
                
                // Add report metadata
                this.addMetadata(doc, data);
                
                // Add score visualization
                this.addScoreSection(doc, data);
                
                // Add detailed analysis
                this.addDetailedAnalysis(doc, data);
                
                // Add suggestions
                this.addSuggestionsSection(doc, data);
                
                // Add footer
                this.addFooter(doc);
                
                doc.end();
            } catch (error) {
                reject(error);
            }
        });
    }

    addHeader(doc, userInfo) {
        // Title
        doc.fontSize(24)
           .font('Helvetica-Bold')
           .fillColor('#3b82f6')
           .text('PLAGIARISM CHECK REPORT', { align: 'center' })
           .moveDown(0.5);
        
        // Subtitle
        doc.fontSize(12)
           .font('Helvetica')
           .fillColor('#666666')
           .text('Generated by Plagiarism Checker Pro', { align: 'center' })
           .moveDown(1);
        
        // Separator line
        doc.strokeColor('#3b82f6')
           .lineWidth(2)
           .moveTo(50, doc.y)
           .lineTo(550, doc.y)
           .stroke()
           .moveDown(1.5);
    }

    addMetadata(doc, data) {
        doc.fontSize(11)
           .font('Helvetica')
           .fillColor('#333333');
        
        const metadata = [
            { label: 'Report ID', value: data.requestId || 'N/A' },
            { label: 'Generated', value: new Date(data.timestamp || Date.now()).toLocaleString() },
            { label: 'Processing Time', value: data.processingTime || 'N/A' },
            { label: 'Text Length', value: `${data.textLength || 0} characters` },
            { label: 'Word Count', value: `${data.wordCount || 0} words` },
            { label: 'Sentence Count', value: `${data.sentenceCount || 0} sentences` }
        ];
        
        let startY = doc.y;
        const colWidth = 250;
        
        metadata.forEach((item, index) => {
            const col = index % 2;
            const row = Math.floor(index / 2);
            const x = 50 + (col * colWidth);
            const y = startY + (row * 20);
            
            doc.font('Helvetica-Bold')
               .fontSize(10)
               .fillColor('#555555')
               .text(item.label + ':', x, y);
            
            doc.font('Helvetica')
               .fillColor('#333333')
               .text(item.value, x + 80, y);
        });
        
        doc.y = startY + (Math.ceil(metadata.length / 2) * 20) + 20;
        doc.moveDown(1);
    }

    addScoreSection(doc, data) {
        const score = data.overallPlagiarism || 0;
        let color, level, description;
        
        if (score >= 80) {
            color = '#ef4444'; // Red
            level = 'HIGH PLAGIARISM';
            description = 'Extensive copying detected. Immediate revision required.';
        } else if (score >= 50) {
            color = '#f59e0b'; // Orange
            level = 'MODERATE PLAGIARISM';
            description = 'Significant similarities detected. Review recommended.';
        } else if (score >= 20) {
            color = '#3b82f6'; // Blue
            level = 'LOW SIMILARITY';
            description = 'Minor similarities detected. Some rewording suggested.';
        } else {
            color = '#10b981'; // Green
            level = 'ORIGINAL CONTENT';
            description = 'Content appears to be mostly original. Good work!';
        }
        
        // Score circle visualization
        const centerX = 300;
        const centerY = doc.y + 60;
        const radius = 50;
        
        // Background circle
        doc.circle(centerX, centerY, radius)
           .fillColor('#f3f4f6')
           .fill();
        
        // Score percentage
        doc.fontSize(36)
           .font('Helvetica-Bold')
           .fillColor(color)
           .text(`${score}%`, centerX - 35, centerY - 20, { width: 70, align: 'center' });
        
        // Score level
        doc.fontSize(14)
           .fillColor(color)
           .text(level, centerX - 60, centerY + 30, { width: 120, align: 'center' });
        
        // Description
        doc.fontSize(10)
           .font('Helvetica')
           .fillColor('#666666')
           .text(description, 50, centerY + 80, { width: 500, align: 'center' });
        
        doc.y = centerY + 120;
        doc.moveDown(1);
        
        // Add warning if needed
        if (score >= 50) {
            doc.fontSize(10)
               .font('Helvetica-Bold')
               .fillColor(color)
               .text('⚠️ IMPORTANT: This score indicates potential academic integrity issues.', 
                     50, doc.y, { width: 500, align: 'center' });
            doc.moveDown(1);
        }
    }

    addDetailedAnalysis(doc, data) {
        // Check if we need a new page
        if (doc.y > 600) {
            doc.addPage();
        }
        
        // Section title
        doc.fontSize(16)
           .font('Helvetica-Bold')
           .fillColor('#3b82f6')
           .text('DETAILED ANALYSIS', 50, doc.y)
           .moveDown(0.5);
        
        const analysis = data.detailedReport;
        if (!analysis) return;
        
        // Sentences analysis
        if (analysis.sentenceAnalysis?.length > 0) {
            const flaggedSentences = analysis.sentenceAnalysis.filter(s => s.isFlagged);
            
            doc.fontSize(12)
               .font('Helvetica-Bold')
               .fillColor('#333333')
               .text('Sentence Analysis:', 50, doc.y);
            
            doc.fontSize(10)
               .font('Helvetica')
               .fillColor('#666666')
               .text(`Total Sentences: ${analysis.sentenceAnalysis.length} | Flagged Sentences: ${flaggedSentences.length}`, 
                     50, doc.y)
               .moveDown(0.5);
            
            // Display flagged sentences
            if (flaggedSentences.length > 0) {
                doc.moveDown(0.5);
                
                flaggedSentences.forEach((sentence, index) => {
                    if (doc.y > 700) {
                        doc.addPage();
                        doc.y = 50;
                    }
                    
                    // Sentence header
                    doc.fontSize(10)
                       .font('Helvetica-Bold')
                       .fillColor('#ef4444')
                       .text(`${index + 1}. Sentence ${sentence.position + 1} (${sentence.similarity}% similarity)`, 
                             60, doc.y);
                    
                    // Sentence text
                    doc.fontSize(9)
                       .font('Helvetica')
                       .fillColor('#333333')
                       .text(this.truncateText(sentence.sentence, 100), 60, doc.y + 12, { width: 450 });
                    
                    doc.y += 30;
                });
            }
            
            doc.moveDown(1);
        }
        
        // Statistics section
        doc.fontSize(12)
           .font('Helvetica-Bold')
           .fillColor('#333333')
           .text('Statistics:', 50, doc.y);
        
        const stats = [
            ['Overall Plagiarism Score', `${data.overallPlagiarism || 0}%`],
            ['Unique Content', `${100 - (data.overallPlagiarism || 0)}%`],
            ['Processing Time', data.processingTime || 'N/A'],
            ['Analysis Date', new Date(data.timestamp || Date.now()).toLocaleDateString()]
        ];
        
        let statsY = doc.y + 15;
        stats.forEach(([label, value], index) => {
            doc.font('Helvetica-Bold').fontSize(10).fillColor('#555555')
               .text(label + ':', 50, statsY + (index * 15));
            doc.font('Helvetica').fillColor('#333333')
               .text(value, 200, statsY + (index * 15));
        });
        
        doc.y = statsY + (stats.length * 15) + 20;
    }

    addSuggestionsSection(doc, data) {
        const suggestions = data.suggestions || [];
        if (suggestions.length === 0) return;
        
        // Check if we need a new page
        if (doc.y > 650) {
            doc.addPage();
            doc.y = 50;
        }
        
        doc.fontSize(12)
           .font('Helvetica-Bold')
           .fillColor('#333333')
           .text('Recommendations:', 50, doc.y)
           .moveDown(0.5);
        
        suggestions.forEach((suggestion, index) => {
            if (doc.y > 750) {
                doc.addPage();
                doc.y = 50;
            }
            
            const bulletX = 60;
            const textX = 70;
            
            // Bullet point
            doc.circle(bulletX, doc.y + 4, 2)
               .fillColor('#3b82f6')
               .fill();
            
            // Suggestion text
            doc.fontSize(10)
               .font('Helvetica')
               .fillColor('#333333')
               .text(suggestion, textX, doc.y, { width: 430 });
            
            doc.y += 20;
        });
        
        doc.moveDown(1);
    }

    addFooter(doc) {
        const pageHeight = 842; // A4 height in points
        const footerY = pageHeight - 50;
        
        // Footer separator
        doc.strokeColor('#e5e7eb')
           .lineWidth(1)
           .moveTo(50, footerY)
           .lineTo(550, footerY)
           .stroke();
        
        // Footer text
        doc.fontSize(9)
           .font('Helvetica')
           .fillColor('#666666')
           .text('Plagiarism Checker Pro • Generated on ' + new Date().toLocaleDateString(), 
                 50, footerY + 10, { width: 250 });
        
        doc.text('Page ' + doc.pageNumber, 500, footerY + 10, { width: 100, align: 'right' });
        
        // Disclaimer
        doc.fontSize(8)
           .fillColor('#999999')
           .text('Disclaimer: This report is for informational purposes only. Always verify results manually.', 
                 50, footerY + 25, { width: 500, align: 'center' });
    }

    truncateText(text, maxLength) {
        if (!text || text.length <= maxLength) return text || '';
        return text.substring(0, maxLength - 3) + '...';
    }
}

module.exports = new PDFService();